########################################################################
# Taps                                                                 #
########################################################################
tap "hashicorp/tap"

########################################################################
# CLI                                                                  #
########################################################################
brew "ansible"
brew "automake"
brew "bash"
brew "bash-completion@2"
brew "cmake"
brew "codex"
brew "coreutils"
brew "curl", link: true
brew "docker-completion"
brew "ffmpeg"
brew "findutils"
brew "gcc"
brew "gdb"
brew "gh"
brew "git"
brew "gradle"
brew "gradle-completion"
brew "grpc"
brew "htop"
brew "imagemagick"
brew "irssi"
brew "jq"
brew "maven"
brew "maven-completion"
brew "moreutils"
brew "neovim"
brew "nmap"
brew "node"
brew "openssl@3"
brew "pip-completion"
brew "protobuf"
brew "pyenv"
brew "readline"
brew "ripgrep"
brew "shellcheck"
brew "spring-completion"
brew "sqlite"
brew "terraform"
brew "tmux"
brew "tree"
brew "vault"
brew "vim"
brew "wget"
brew "wireshark"
brew "zellij"

########################################################################
# Apps                                                                 #
########################################################################
cask "alacritty"
cask "alfred"
cask "docker"
cask "docker-desktop"
cask "firefox"
cask "google-chrome"
cask "github"
cask "jetbrains-toolbox"
cask "font-monaspace"
cask "maccy"
cask "ngrok"
cask "nordvpn"
cask "notion"
cask "rectangle"
cask "slack"
cask "spotify"
cask "the-unarchiver"
cask "visualvm"
cask "vlc"
cask "whatsapp"
cask "zed"
cask "zoom"
