########################################################################
# Taps                                                                 #
########################################################################
tap "hashicorp/tap"
tap "mongodb/brew"

########################################################################
# CLI                                                                  #
########################################################################
brew "ack"
brew "ansible"
brew "autojump"
brew "automake"
brew "awscli"
brew "bash"
brew "bash-completion@2"
brew "cmake"
brew "codex"
brew "consul"
brew "coreutils"
brew "curl", link: true
brew "docker-completion"
brew "ffmpeg"
brew "findutils"
brew "gcc"
brew "gdb"
brew "gh"
brew "git"
brew "gradle"
brew "gradle-completion"
brew "grpc"
brew "htop"
brew "httpie"
brew "imagemagick"
brew "irssi"
brew "jq"
brew "maven"
brew "maven-completion"
brew "moreutils"
brew "neovim"
brew "nmap"
brew "node"
brew "nomad"
brew "ollama"
brew "openssl"
brew "php"
brew "pip-completion"
brew "protobuf"
brew "pyenv"
brew "rbenv"
brew "readline"
brew "ripgrep"
brew "ruby"
brew "spring-completion"
brew "sqlite"
brew "terraform"
brew "the_silver_searcher"
brew "tmux"
brew "tree"
brew "vault"
brew "vim"
brew "watch"
brew "watchman"
brew "wget"
brew "wireshark"
brew "zellij"

########################################################################
# Apps                                                                 #
########################################################################
cask "alacritty"
cask "alfred"
cask "docker"
cask "firefox"
cask "google-chrome"
cask "github"
cask "iterm2"
cask "jetbrains-toolbox"
cask "localsend"
cask "font-monaspace"
cask "maccy"
cask "ngrok"
cask "nordvpn"
cask "notion"
cask "ollama-app"
cask "rectangle"
cask "slack"
cask "spotify"
cask "stats"
cask "the-unarchiver"
cask "visualvm"
cask "vlc"
cask "whatsapp"
cask "zed"
cask "zoom"
